name: flutter_glow
description: complete and easy to use flutter glow ui kit that help you to create and use glow widgets.
  also you can create your own GlowTheme.
version: 0.1.2
repository: https://github.com/payam-zahedi/flutter-glow
issue_tracker: https://github.com/payam-zahedi/flutter-glow/issues
homepage: https://github.com/payam-zahedi/flutter-glow

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
