name: flutter_glow
version: 0.3.2
description: A package for adding glow effects to text and widgets in Flutter.

repository: https://github.com/yourusername/flutter-glow-fixed
issue_tracker: https://github.com/yourusername/flutter-glow-fixed/issues
homepage: https://github.com/yourusername/flutter-glow-fixed

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.4
