name: flutter_glow
description: complete and easy to use flutter glow ui kit.
version: 0.1.0
repository: https://github.com/payam-zahedi/flutter-glow
issue_tracker: https://github.com/payam-zahedi/flutter-glow/issues
homepage: https://github.com/payam-zahedi/flutter-glow

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
